# Generated by Django 5.1.4 on 2026-06-26 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipmentinspection_equipmenttransfer'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خیر')),
                ('type', models.CharField(choices=[('individual', 'حقیقی'), ('organization', 'حقوقی')], default='individual', max_length=20, verbose_name='نوع')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی/شناسه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('anonymous', models.BooleanField(default=False, verbose_name='ناشناس')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='organization.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'خیر',
                'verbose_name_plural': 'خیرین',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (ریال)')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('transfer', 'انتقال بانکی'), ('online', 'درگاه آنلاین')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='شماره پیگیری')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='بابت')),
                ('donated_at', models.DateField(blank=True, null=True, verbose_name='تاریخ اهدا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_donations', to='organization.branch', verbose_name='شعبه')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_donations', to='community.donor', verbose_name='خیر')),
            ],
            options={
                'verbose_name': 'اهدای نقدی',
                'verbose_name_plural': 'اهدای\u200cهای نقدی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام قلم اهدایی')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='ارزش برآوردی (ریال)')),
                ('donated_at', models.DateField(blank=True, null=True, verbose_name='تاریخ اهدا')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_donations', to='organization.branch', verbose_name='شعبه')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_donations', to='community.donor', verbose_name='خیر')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='equipment.equipment', verbose_name='تجهیز ثبت\u200cشده')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_equipment_donations', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'اهدای تجهیز',
                'verbose_name_plural': 'اهدای\u200cهای تجهیزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('skills', models.CharField(blank=True, max_length=300, verbose_name='مهارت\u200cها')),
                ('availability', models.CharField(blank=True, max_length=200, verbose_name='در دسترس بودن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='organization.branch', verbose_name='شعبه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'داوطلب',
                'verbose_name_plural': 'داوطلبان',
                'ordering': ['full_name'],
            },
        ),
    ]
