# Generated by Django 5.1.4 on 2026-06-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'سالم'), ('minor_issue', 'نقص جزئی'), ('needs_repair', 'نیازمند تعمیر'), ('fail', 'مردود')], default='pass', max_length=20, verbose_name='نتیجه بازرسی')),
                ('checklist', models.JSONField(blank=True, default=dict, verbose_name='چک\u200cلیست')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipment')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='بازرس')),
            ],
            options={
                'verbose_name': 'بازرسی تجهیز',
                'verbose_name_plural': 'بازرسی\u200cهای تجهیزات',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('in_transit', 'در حال انتقال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت انتقال')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل انتقال')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='equipment.equipment')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='organization.unit', verbose_name='از واحد')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='organization.unit', verbose_name='به واحد')),
            ],
            options={
                'verbose_name': 'انتقال تجهیز',
                'verbose_name_plural': 'انتقال\u200cهای تجهیزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
