# Generated by Django 5.1.4 on 2026-06-26 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipmentinspection_equipmenttransfer'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'جزئی'), ('moderate', 'متوسط'), ('major', 'شدید'), ('irreparable', 'غیرقابل تعمیر')], default='minor', max_length=20, verbose_name='شدت آسیب')),
                ('description', models.TextField(verbose_name='شرح آسیب')),
                ('resolved', models.BooleanField(default=False, verbose_name='رسیدگی شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='equipment.equipment', verbose_name='تجهیز')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='loans.loan', verbose_name='امانت مرتبط')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش آسیب',
                'verbose_name_plural': 'گزارش\u200cهای آسیب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال تعمیر'), ('awaiting_parts', 'در انتظار قطعه'), ('completed', 'تکمیل شده'), ('decommissioned', 'اسقاط')], default='open', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='شرح کار')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='هزینه (ریال)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='maintenance.damagereport', verbose_name='گزارش آسیب')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='equipment.equipment', verbose_name='تجهیز')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='equipment.supplier', verbose_name='تأمین\u200cکننده قطعه')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'تعمیر',
                'verbose_name_plural': 'تعمیرها',
                'ordering': ['-created_at'],
            },
        ),
    ]
