# Generated by Django 5.1.4 on 2026-06-26 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipmentinspection_equipmenttransfer'),
        ('organization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='نسبت با بیمار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تحویل\u200cگیرنده',
                'verbose_name_plural': 'تحویل\u200cگیرندگان',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mobility', 'تجهیزات حرکتی'), ('respiratory', 'تجهیزات تنفسی'), ('bed_care', 'تجهیزات بستری'), ('rehabilitation', 'تجهیزات توانبخشی'), ('monitoring', 'تجهیزات پایش و مراقبت'), ('other', 'سایر')], max_length=30, verbose_name='دسته\u200cبندی موردنیاز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'عادی'), ('normal', 'متوسط'), ('high', 'بالا'), ('urgent', 'اضطراری')], default='normal', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('fulfilled', 'تأمین شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='patients.patient', verbose_name='بیمار')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='organization.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'درخواست تجهیز',
                'verbose_name_plural': 'درخواست\u200cهای تجهیزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'تخصیص یافته'), ('delivered', 'تحویل داده شده'), ('returned', 'بازگشت داده شده'), ('disinfected', 'ضدعفونی شده'), ('closed', 'بسته شده'), ('overdue', 'معوق')], default='assigned', max_length=20, verbose_name='وضعیت')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='موعد بازگشت')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بازگشت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.borrower', verbose_name='تحویل\u200cگیرنده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='equipment.equipment', verbose_name='تجهیز')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='patients.patient', verbose_name='بیمار')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.equipmentrequest', verbose_name='درخواست مرتبط')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='organization.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'امانت',
                'verbose_name_plural': 'امانت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commitment', 'تعهدنامه'), ('guarantor', 'ضامن'), ('promissory', 'سفته'), ('cheque', 'چک'), ('deposit', 'ودیعه نقدی')], max_length=20, verbose_name='نوع تضمین')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='شماره/مرجع')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ (ریال)')),
                ('guarantor_name', models.CharField(blank=True, max_length=200, verbose_name='نام ضامن')),
                ('guarantor_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن ضامن')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('returned', models.BooleanField(default=False, verbose_name='مسترد شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='loans.loan', verbose_name='امانت')),
            ],
            options={
                'verbose_name': 'تضمین',
                'verbose_name_plural': 'تضمین\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
